# Generated by Django 4.2.26 on 2025-12-02 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Exitoso'), ('login_failed', 'Login Fallido'), ('logout', 'Logout'), ('password_change', 'Cambio de Contraseña'), ('password_reset', 'Reset de Contraseña'), ('token_refresh', 'Refresh de Token'), ('account_locked', 'Cuenta Bloqueada')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField()),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Autenticación',
                'verbose_name_plural': 'Logs de Autenticación',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='users_authe_timesta_a460df_idx'), models.Index(fields=['username', '-timestamp'], name='users_authe_usernam_04f44e_idx'), models.Index(fields=['ip_address', '-timestamp'], name='users_authe_ip_addr_4a3aa5_idx')],
            },
        ),
    ]
